-- Lead-Details capture flag + contact email.
-- The GH runner (zoho-sent-runner) extracts the lead-details block (Enquiry № /
-- Source / Location / POC / Mobile / Email / "Lead generated by") from the first
-- 2-5 Zoho comments. detailsCaptured defaults to 0 for EVERY existing estimate
-- so the next 15-min pass backfills all of them; it flips to 1 as soon as ANY
-- detail field is stored (cheapest mode — the capture loop stops at first data).
-- While 0, the runner's no-change fingerprint path stays disabled so the
-- estimate keeps re-entering the 15-min AI/detail-capture loop until the sales
-- agent posts the lead block (which can take up to ~40 minutes).
ALTER TABLE Estimate ADD COLUMN detailsCaptured INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Estimate ADD COLUMN contactEmail TEXT;
CREATE INDEX IF NOT EXISTS idx_estimate_details_captured ON Estimate(detailsCaptured);