// lead-details.ts — lead-block storage, shared by Worker + Express.
// Persists the runner-extracted chips (enquiry/source/location/contact).
// NOTE (founder rule): "Lead generated by" NEVER writes Estimate.createdBy —
// the By field comes ONLY from the mapping B2B enquiry
// (../enquiries/estimate-link.ts). The extracted name still counts toward
// the 3-field validity gate, then is discarded.
// Retry budget: <3-field captures consume one attempt; at MAX attempts the
// estimate gives up (detailsFailed) until genuinely new comments re-admit it.
import { prisma } from '../../shared/prisma';

export const MAX_DETAILS_ATTEMPTS = 10;

export interface LeadDetailRow {
  estimateId: string;
  enquiryNumber?: string | null;
  sourceLead?: string | null;
  location?: string | null;
  contactName?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  leadGeneratedBy?: string | null;
}

export async function applyLeadDetails(
  rows: LeadDetailRow[],
): Promise<{ updated: number; attempted: number; failed: number }> {
  let updated = 0;
  let attempted = 0;
  let failed = 0;

  const DETAIL_FIELDS = ['enquiryNumber', 'sourceLead', 'location', 'contactName', 'contactPhone', 'contactEmail', 'leadGeneratedBy'] as const;

  for (const r of rows || []) {
    if (!r?.estimateId) continue;
    const data: Record<string, unknown> = {};
    if (r.enquiryNumber !== undefined) data.enquiryNumber = r.enquiryNumber ? String(r.enquiryNumber) : null;
    if (r.sourceLead !== undefined) data.sourceLead = r.sourceLead ? String(r.sourceLead) : null;
    if (r.location !== undefined) data.location = r.location ? String(r.location) : null;
    if (r.contactName !== undefined) data.contactName = r.contactName ? String(r.contactName) : null;
    if (r.contactPhone !== undefined) data.contactPhone = r.contactPhone ? String(r.contactPhone) : null;
    if (r.contactEmail !== undefined) data.contactEmail = r.contactEmail ? String(r.contactEmail) : null;
    // leadGeneratedBy is gate-only (counts toward the 3-field validity
    // threshold below) — it never writes createdBy (enquiry-only rule).
    const detailFields = DETAIL_FIELDS.filter((k) => {
      const v = (r as any)[k];
      return v !== undefined && v !== null && String(v).length > 0;
    });
    // Validity gate: <3 fields consumes a retry attempt instead of storing.
    if (detailFields.length < 3) {
      attempted++;
      try {
        const cur = await (prisma as any).estimate.findUnique({
          where: { estimateId: r.estimateId },
          select: { detailsAttempts: true, detailsCaptured: true, detailsFailed: true },
        });
        if (cur && !cur.detailsCaptured) {
          const attempts = (Number((cur as any).detailsAttempts) || 0) + 1;
          const nowFailed = attempts >= MAX_DETAILS_ATTEMPTS;
          await (prisma as any).estimate.update({
            where: { estimateId: r.estimateId },
            data: { detailsAttempts: attempts, detailsFailed: nowFailed ? true : (cur as any).detailsFailed },
          });
          if (nowFailed && !(cur as any).detailsFailed) failed++;
        }
      } catch (e: any) {
        console.warn({ err: e?.message, estimateId: r.estimateId }, 'lead-details attempt-count update failed');
      }
      continue;
    }
    data.detailsCaptured = true;
    data.detailsAttempts = 0;
    data.detailsFailed = false;
    try {
      await (prisma as any).estimate.update({ where: { estimateId: r.estimateId }, data });
      updated++;
    } catch (e: any) {
      console.warn({ err: e?.message, estimateId: r.estimateId }, 'lead-details update failed');
    }
  }
  return { updated, attempted, failed };
}
