// AUTO-GENERATED by founder-os_backend/scripts/gen-automation-registry.mjs — DO NOT EDIT.
// Regenerate by running the backend build (build-worker.mjs) or
// `node founder-os_backend/scripts/gen-automation-registry.mjs`.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
// @ts-nocheck

// slug → permission scope for each automation dashboard.
// A dashboard without a declared scope (rule.json `scope`) maps to "automations".
export const DASHBOARD_SCOPE_MAP: Record<string, string> = {
  'dpp-prices-dashboard': "dpp",
  'enquiry-tracker': "enquiries",
  'enterprise-operations-analytics': "enterprise-ops",
  'neodove-telecaller-report': "neodove",
  'telecalling': "automations",
  'telecalling-agent-analysis': "sheet-analysis",
  'wa-engine-monitor': "wa-engine",
  'whatsapp-autopilot': "autopilot",
  'whatsapp-marketing': "whatsapp-marketing",
  'zoho-sent-analyzer': "zoho",
};

export const AUTOMATION_DASHBOARDS: string[] = [
  'dpp-prices-dashboard',
  'enquiry-tracker',
  'enterprise-operations-analytics',
  'neodove-telecaller-report',
  'telecalling',
  'telecalling-agent-analysis',
  'wa-engine-monitor',
  'whatsapp-autopilot',
  'whatsapp-marketing',
  'zoho-sent-analyzer',
];
