// Mock Telecaller Dataset
export const mockTelecallerData = {
  configured: false,
  clientEmail: "sheets-reader@founder-os.iam.gserviceaccount.com",
  headers: [
    "Date",
    "Employee Name",
    "Work Assigned",
    "Attendance Status",
    "Total Connected Calls Count",
    "Busy",
    "Outgoing Calls Count",
    "Wrong Number",
    "Not Interested",
    "Callback",
    "Estimates Resent",
    "Estimates Created",
    "Followups",
    "Total SO Created- Count",
    "Payment Received",
    "Total SO Amount-Rupees",
    "Total Call Duration",
    "Drive Link",
    "Remarks",
    "Standard Hours",
    "Leads From Incoming",
    "Leads From Outgoing",
    "Leads From AI"
  ],
  rows: [
    // Day 1: 18-Jun-26
    { _rowId: "tc1", Date: "18-Jun-26", "Employee Name": "Heena", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "32", Busy: "0", "Outgoing Calls Count": "151", "Wrong Number": "0", "Not Interested": "0", Callback: "3", "Estimates Resent": "0", "Estimates Created": "0", Followups: "3", "Total SO Created- Count": "0", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "19m 54s", "Drive Link": "https://drive.google.com/open?id=1MPOTCj0KATcLXofz8AJGmcQEcaw5ouLd", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "2", "Leads From Outgoing": "1", "Leads From AI": "4" },
    { _rowId: "tc2", Date: "18-Jun-26", "Employee Name": "Deepak", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "25", Busy: "0", "Outgoing Calls Count": "72", "Wrong Number": "0", "Not Interested": "10", Callback: "1", "Estimates Resent": "0", "Estimates Created": "1", Followups: "1", "Total SO Created- Count": "1", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "33m 55s", "Drive Link": "https://drive.google.com/open?id=1rKiPAcxLKlO0lZsC-j4KMiCH9Jwml9ju", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "1", "Leads From Outgoing": "0", "Leads From AI": "1" },
    { _rowId: "tc3", Date: "18-Jun-26", "Employee Name": "Raja", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "40", Busy: "0", "Outgoing Calls Count": "114", "Wrong Number": "6", "Not Interested": "6", Callback: "2", "Estimates Resent": "0", "Estimates Created": "0", Followups: "2", "Total SO Created- Count": "1", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "41m 20s", "Drive Link": "https://drive.google.com/open?id=1oG-A7AgWBLIQ2fg-U2BoY91NRSH5Xw2L", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "3", "Leads From Outgoing": "2", "Leads From AI": "2" },
    { _rowId: "tc4", Date: "18-Jun-26", "Employee Name": "Rani", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "30", Busy: "1", "Outgoing Calls Count": "101", "Wrong Number": "0", "Not Interested": "0", Callback: "0", "Estimates Resent": "0", "Estimates Created": "0", Followups: "0", "Total SO Created- Count": "0", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "24m 29s", "Drive Link": "https://drive.google.com/open?id=1AXYmwGWBr_ZNvCkYo8s8WVC4SiMpCwqo", Remarks: "35 calls extra.", "Standard Hours": "18", "Leads From Incoming": "0", "Leads From Outgoing": "1", "Leads From AI": "0" },
    { _rowId: "tc5", Date: "18-Jun-26", "Employee Name": "Muskan", "Work Assigned": "ESTIMATES FOLLOW UP", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "59", Busy: "1", "Outgoing Calls Count": "15", "Wrong Number": "0", "Not Interested": "0", Callback: "1", "Estimates Resent": "41", "Estimates Created": "41", Followups: "1", "Total SO Created- Count": "2", "Payment Received": "2", "Total SO Amount-Rupees": "43601", "Total Call Duration": "54m 4s", "Drive Link": "https://drive.google.com/open?id=1sMAKYR7pYc-pp2YP2lrJ40bPc6veDu16", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "8", "Leads From Outgoing": "4", "Leads From AI": "10" },
    { _rowId: "tc6", Date: "18-Jun-26", "Employee Name": "Samarjeet", "Work Assigned": "BOTH", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "45", Busy: "0", "Outgoing Calls Count": "7", "Wrong Number": "10", "Not Interested": "0", Callback: "1", "Estimates Resent": "28", "Estimates Created": "28", Followups: "1", "Total SO Created- Count": "3", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "50 min approx", "Drive Link": "https://drive.google.com/open?id=12fyKBHW5bbAYeriT14ke4opzSbYfThw8", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "5", "Leads From Outgoing": "3", "Leads From AI": "7" },

    // Day 2: 19-Jun-26
    { _rowId: "tc7", Date: "19-Jun-26", "Employee Name": "Heena", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "28", Busy: "1", "Outgoing Calls Count": "142", "Wrong Number": "1", "Not Interested": "2", Callback: "4", "Estimates Resent": "0", "Estimates Created": "0", Followups: "5", "Total SO Created- Count": "0", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "18m 10s", "Drive Link": "https://drive.google.com/open?id=1MPOTCj0KATcLXofz8AJGmcQEcaw5ouLd", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "3", "Leads From Outgoing": "1", "Leads From AI": "5" },
    { _rowId: "tc8", Date: "19-Jun-26", "Employee Name": "Deepak", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "31", Busy: "0", "Outgoing Calls Count": "85", "Wrong Number": "0", "Not Interested": "8", Callback: "2", "Estimates Resent": "0", "Estimates Created": "2", Followups: "2", "Total SO Created- Count": "1", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "26m 45s", "Drive Link": "https://drive.google.com/open?id=1rKiPAcxLKlO0lZsC-j4KMiCH9Jwml9ju", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "1", "Leads From Outgoing": "1", "Leads From AI": "2" },
    { _rowId: "tc9", Date: "19-Jun-26", "Employee Name": "Raja", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "44", Busy: "1", "Outgoing Calls Count": "120", "Wrong Number": "4", "Not Interested": "5", Callback: "3", "Estimates Resent": "0", "Estimates Created": "0", Followups: "3", "Total SO Created- Count": "2", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "45m 12s", "Drive Link": "https://drive.google.com/open?id=1oG-A7AgWBLIQ2fg-U2BoY91NRSH5Xw2L", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "4", "Leads From Outgoing": "3", "Leads From AI": "3" },
    { _rowId: "tc10", Date: "19-Jun-26", "Employee Name": "Rani", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "36", Busy: "2", "Outgoing Calls Count": "110", "Wrong Number": "0", "Not Interested": "1", Callback: "1", "Estimates Resent": "0", "Estimates Created": "0", Followups: "1", "Total SO Created- Count": "0", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "28m 15s", "Drive Link": "https://drive.google.com/open?id=1AXYmwGWBr_ZNvCkYo8s8WVC4SiMpCwqo", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "0", "Leads From Outgoing": "0", "Leads From AI": "1" },
    { _rowId: "tc11", Date: "19-Jun-26", "Employee Name": "Muskan", "Work Assigned": "ESTIMATES FOLLOW UP", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "62", Busy: "0", "Outgoing Calls Count": "18", "Wrong Number": "0", "Not Interested": "0", Callback: "2", "Estimates Resent": "45", "Estimates Created": "45", Followups: "2", "Total SO Created- Count": "3", "Payment Received": "3", "Total SO Amount-Rupees": "75000", "Total Call Duration": "62m 5s", "Drive Link": "https://drive.google.com/open?id=1sMAKYR7pYc-pp2YP2lrJ40bPc6veDu16", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "7", "Leads From Outgoing": "5", "Leads From AI": "9" },
    { _rowId: "tc12", Date: "19-Jun-26", "Employee Name": "Samarjeet", "Work Assigned": "BOTH", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "48", Busy: "1", "Outgoing Calls Count": "12", "Wrong Number": "8", "Not Interested": "0", Callback: "2", "Estimates Resent": "32", "Estimates Created": "32", Followups: "2", "Total SO Created- Count": "2", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "48m 30s", "Drive Link": "https://drive.google.com/open?id=12fyKBHW5bbAYeriT14ke4opzSbYfThw8", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "6", "Leads From Outgoing": "4", "Leads From AI": "8" },

    // Day 3: 20-Jun-26
    { _rowId: "tc13", Date: "20-Jun-26", "Employee Name": "Heena", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "38", Busy: "0", "Outgoing Calls Count": "160", "Wrong Number": "0", "Not Interested": "1", Callback: "5", "Estimates Resent": "0", "Estimates Created": "0", Followups: "4", "Total SO Created- Count": "1", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "22m 30s", "Drive Link": "https://drive.google.com/open?id=1MPOTCj0KATcLXofz8AJGmcQEcaw5ouLd", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "4", "Leads From Outgoing": "2", "Leads From AI": "6" },
    { _rowId: "tc14", Date: "20-Jun-26", "Employee Name": "Deepak", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "27", Busy: "1", "Outgoing Calls Count": "78", "Wrong Number": "0", "Not Interested": "7", Callback: "1", "Estimates Resent": "0", "Estimates Created": "1", Followups: "1", "Total SO Created- Count": "0", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "31m 15s", "Drive Link": "https://drive.google.com/open?id=1rKiPAcxLKlO0lZsC-j4KMiCH9Jwml9ju", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "2", "Leads From Outgoing": "1", "Leads From AI": "1" },
    { _rowId: "tc15", Date: "20-Jun-26", "Employee Name": "Raja", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "46", Busy: "0", "Outgoing Calls Count": "135", "Wrong Number": "5", "Not Interested": "4", Callback: "4", "Estimates Resent": "0", "Estimates Created": "0", Followups: "4", "Total SO Created- Count": "3", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "48m 55s", "Drive Link": "https://drive.google.com/open?id=1oG-A7AgWBLIQ2fg-U2BoY91NRSH5Xw2L", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "5", "Leads From Outgoing": "3", "Leads From AI": "5" },
    { _rowId: "tc16", Date: "20-Jun-26", "Employee Name": "Rani", "Work Assigned": "TELLE CALLER", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "32", Busy: "1", "Outgoing Calls Count": "95", "Wrong Number": "0", "Not Interested": "0", Callback: "1", "Estimates Resent": "0", "Estimates Created": "0", Followups: "1", "Total SO Created- Count": "0", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "22m 40s", "Drive Link": "https://drive.google.com/open?id=1AXYmwGWBr_ZNvCkYo8s8WVC4SiMpCwqo", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "1", "Leads From Outgoing": "0", "Leads From AI": "2" },
    { _rowId: "tc17", Date: "20-Jun-26", "Employee Name": "Muskan", "Work Assigned": "ESTIMATES FOLLOW UP", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "68", Busy: "1", "Outgoing Calls Count": "22", "Wrong Number": "0", "Not Interested": "0", Callback: "3", "Estimates Resent": "50", "Estimates Created": "50", Followups: "3", "Total SO Created- Count": "4", "Payment Received": "4", "Total SO Amount-Rupees": "95000", "Total Call Duration": "70m 10s", "Drive Link": "https://drive.google.com/open?id=1sMAKYR7pYc-pp2YP2lrJ40bPc6veDu16", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "9", "Leads From Outgoing": "6", "Leads From AI": "12" },
    { _rowId: "tc18", Date: "20-Jun-26", "Employee Name": "Samarjeet", "Work Assigned": "BOTH", "Attendance Status": "FULL DAY", "Total Connected Calls Count": "42", Busy: "0", "Outgoing Calls Count": "10", "Wrong Number": "6", "Not Interested": "0", Callback: "1", "Estimates Resent": "35", "Estimates Created": "35", Followups: "2", "Total SO Created- Count": "1", "Payment Received": "0", "Total SO Amount-Rupees": "0", "Total Call Duration": "45m 20s", "Drive Link": "https://drive.google.com/open?id=12fyKBHW5bbAYeriT14ke4opzSbYfThw8", Remarks: "", "Standard Hours": "18", "Leads From Incoming": "5", "Leads From Outgoing": "3", "Leads From AI": "6" }
  ]
};

// Mock Sales Pipeline Dataset
export const mockPipelineData = {
  configured: false,
  clientEmail: "sheets-reader@founder-os.iam.gserviceaccount.com",
  headers: ["Date", "Customer Name", "Product Category", "Order Value (INR)", "Agent", "Status", "Probability (%)"],
  rows: [
    { _rowId: "1", Date: "2026-07-01", "Customer Name": "Sanjay Uttam Agro", "Product Category": "Milling Belts", "Order Value (INR)": "75000", Agent: "Samarth Gupta", Status: "Negotiation", "Probability (%)": "80" },
    { _rowId: "2", Date: "2026-07-03", "Customer Name": "Aarya Industries", "Product Category": "Bag Closer Thread", "Order Value (INR)": "20000", Agent: "Muskan", Status: "Qualified", "Probability (%)": "60" },
    { _rowId: "3", Date: "2026-07-05", "Customer Name": "Sam Enterprises", "Product Category": "Machine Spares", "Order Value (INR)": "120000", Agent: "Alice Vance", Status: "Proposal", "Probability (%)": "70" },
    { _rowId: "4", Date: "2026-07-07", "Customer Name": "JMP Industry", "Product Category": "Milling Accessories", "Order Value (INR)": "45000", Agent: "Muskan", Status: "Won", "Probability (%)": "100" },
    { _rowId: "5", Date: "2026-07-10", "Customer Name": "Janani Foodtek", "Product Category": "Milling Belts", "Order Value (INR)": "150000", Agent: "Samarth Gupta", Status: "Lost", "Probability (%)": "0" },
    { _rowId: "6", Date: "2026-07-11", "Customer Name": "United Carbon", "Product Category": "Filter Cloth", "Order Value (INR)": "95000", Agent: "Alice Vance", Status: "Negotiation", "Probability (%)": "90" },
    { _rowId: "7", Date: "2026-07-12", "Customer Name": "Shree Bhagwati Udyog", "Product Category": "Machine Spares", "Order Value (INR)": "35000", Agent: "SALES3", Status: "Won", "Probability (%)": "100" }
  ]
};

// Mock CRM Dispatch Tracker Dataset
export const mockCrmTrackerData = {
  configured: false,
  clientEmail: "sheets-reader@founder-os.iam.gserviceaccount.com",
  headers: [
    "S.No.", "Date", "SO Number", "Estimate Number", "Company Name", "Amount", "Client Confirmation", "Transporter", 
    "Stock Confirmation", "Client/Stock Confirmation Date", "PO", "Contact Person", "Contact Number", "Mail ID", 
    "Delivery Status", "Pending Items", "Documents", "Doc. To Client Status", "Scheduled Date", "Dispatch Date", 
    "On Time Status-BUI", "Tentative Delivery Date BUI", "Delivery Date to Client", "On Time Status-Client", 
    "Remarks", "Payment Method", "Payment Status", "Total Amount", "Amount Paid", "Payment Due"
  ],
  rows: [
    { _rowId: "crm1", "S.No.": "91", Date: "2026-05-26", "SO Number": "SO-11188", "Estimate Number": "EST-022021", "Company Name": "Kesari Roller Flour Mills (KA)", Amount: "246,817.00", "Client Confirmation": "Yes", Transporter: "DTDC COURIER", "Stock Confirmation": "Partially Available", "Client/Stock Confirmation Date": "26-May-26", PO: "", "Contact Person": "Rajender Gupta", "Contact Number": "9350290330", "Mail ID": "kesariflour@gmail.com", "Delivery Status": "Partially Dispatched", "Pending Items": "ITEM 4,7,8,10,11", Documents: "", "Doc. To Client Status": "", "Scheduled Date": "26-May-26", "Dispatch Date": "28-May-26", "On Time Status-BUI": "Delayed", "Tentative Delivery Date BUI": "2-Jun-26", "Delivery Date to Client": "", "On Time Status-Client": "Delivery Date Missing", Remarks: "DELIVERED 54GG-31.8.2026,9XXX-31.8.2026,13XXX-30.9.2026,66GG-31.8.2026,50GG-31.8.2026", "Payment Method": "Against Delivery", "Payment Status": "", "Total Amount": "246,817.00", "Amount Paid": "", "Payment Due": "246,817.00" },
    { _rowId: "crm2", "S.No.": "98", Date: "2026-05-23", "SO Number": "SO-11181", "Estimate Number": "EST-022006", "Company Name": "G Mart Foods Pvt Ltd", Amount: "59,449.00", "Client Confirmation": "Yes", Transporter: "DIVINE LOGISTICS,DTDC COURIER", "Stock Confirmation": "Partially Available", "Client/Stock Confirmation Date": "23-May-26", PO: "102", "Contact Person": "Komal Singh ", "Contact Number": "8859666605", "Mail ID": "gmart.foods2@gmail.com", "Delivery Status": "Partially Dispatched", "Pending Items": "ITEM 6", Documents: "", "Doc. To Client Status": "", "Scheduled Date": "23-May-26", "Dispatch Date": "27-May-26", "On Time Status-BUI": "Delayed", "Tentative Delivery Date BUI": "28-May-26", "Delivery Date to Client": "", "On Time Status-Client": "Delivery Date Missing", Remarks: "DTDC DELIVERED 50GG-31.8.2026", "Payment Method": "Advance", "Payment Status": "Full Payment", "Total Amount": "59,449.00", "Amount Paid": "", "Payment Due": "59,449.00" },
    { _rowId: "crm3", "S.No.": "146", Date: "2026-05-09", "SO Number": "SO-11132", "Estimate Number": "EST-021830", "Company Name": "Goa Roller Flour Mill Pvt Ltd (GA)", Amount: "103,315.00", "Client Confirmation": "Yes", Transporter: "DTDC COURIER", "Stock Confirmation": "Available", "Client/Stock Confirmation Date": "9-May-26", PO: "", "Contact Person": "Hitendra Chaudhary", "Contact Number": "98226 48285", "Mail ID": "", "Delivery Status": "Partially Dispatched", "Pending Items": "ITEM NO 1,2,,6", Documents: "", "Doc. To Client Status": "", "Scheduled Date": "9-May-26", "Dispatch Date": "9-May-26", "On Time Status-BUI": "On Time", "Tentative Delivery Date BUI": "15-May-26", "Delivery Date to Client": "", "On Time Status-Client": "Delivery Date Missing", Remarks: "DELIVERED", "Payment Method": "Against Delivery", "Payment Status": "", "Total Amount": "103,315.00", "Amount Paid": "", "Payment Due": "103,315.00" },
    { _rowId: "crm4", "S.No.": "8", Date: "2026-06-12", "SO Number": "SO-11256", "Estimate Number": "EST-022204", "Company Name": "SRG Products LLP", Amount: "38,521.00", "Client Confirmation": "Yes", Transporter: "DTDC COURIER", "Stock Confirmation": "Available", "Client/Stock Confirmation Date": "12-Jun-26", PO: "ITEM 4 PO-159", "Contact Person": "SRG Products LLP ", "Contact Number": "97195 64419", "Mail ID": "sanjaymudgal69@gmail.com", "Delivery Status": "Partially Dispatched", "Pending Items": "ITEM NO 2", Documents: "", "Doc. To Client Status": "", "Scheduled Date": "12-Jun-26", "Dispatch Date": "16-Jun-26", "On Time Status-BUI": "Delayed", "Tentative Delivery Date BUI": "19-Jun-26", "Delivery Date to Client": "", "On Time Status-Client": "Delivery Date Missing", Remarks: "DELIVERED,50GG-31.8.2026", "Payment Method": "Against Delivery", "Payment Status": "", "Total Amount": "38,521.00", "Amount Paid": "", "Payment Due": "38,521.00" },
    { _rowId: "crm5", "S.No.": "31", Date: "2026-06-08", "SO Number": "SO-11233", "Estimate Number": "EST-021875", "Company Name": "Numix Industries Pvt Ltd", Amount: "372.00", "Client Confirmation": "Yes", Transporter: "", "Stock Confirmation": "Partially Available", "Client/Stock Confirmation Date": "8-Jun-26", PO: "", "Contact Person": "Yuvraj Singh ", "Contact Number": "7351879896", "Mail ID": "", "Delivery Status": "Partially Dispatched", "Pending Items": "", Documents: "", "Doc. To Client Status": "", "Scheduled Date": "20-Jun-26", "Dispatch Date": "", "On Time Status-BUI": "", "Tentative Delivery Date BUI": "", "Delivery Date to Client": "", "On Time Status-Client": "Dates Missing", Remarks: "SAMPLE GYA HAI", "Payment Method": "Advance", "Payment Status": "Full Payment", "Total Amount": "372.00", "Amount Paid": "", "Payment Due": "372.00" },
    { _rowId: "crm6", "S.No.": "32", Date: "2026-06-06", "SO Number": "SO-11232", "Estimate Number": "EST-021144", "Company Name": "Gajraula Roller Flour Mill", Amount: "79,002.00", "Client Confirmation": "Yes", Transporter: "", "Stock Confirmation": "Available", "Client/Stock Confirmation Date": "6-Jun-26", PO: "138", "Contact Person": "Anil Kumar Jain", "Contact Number": "9837090801", "Mail ID": "", "Delivery Status": "Partially Dispatched", "Pending Items": "", Documents: "", "Doc. To Client Status": "", "Scheduled Date": "13-Jun-26", "Dispatch Date": "", "On Time Status-BUI": "", "Tentative Delivery Date BUI": "", "Delivery Date to Client": "", "On Time Status-Client": "Dates Missing", Remarks: "HUMNE GAJRAULA KO SAMPLE BHEJA HAI WO BTYEGA KONSA USE CHAHIYE", "Payment Method": "Against Delivery", "Payment Status": "", "Total Amount": "79,002.00", "Amount Paid": "", "Payment Due": "79,002.00" }
  ]
};
