// estimate-link.ts — Enquiry ↔ Zoho Estimate link (single source of truth).
//
// Link: Enquiry.estNumber = Estimate.estimateNumber (exact, trimmed).
// "Lead generated by" (Estimate.createdBy) is mapped ENTIRELY from which
// agent created the enquiry (Enquiry.assignedAgentId) — the ONLY writer.
// First-Zoho-comment creator inference was REMOVED (founder rule): no
// fallback anywhere; unmapped estimates simply show no By.
import { prisma } from '../../shared/prisma';

export function normalizeEstNumber(s: unknown): string {
  return String(s ?? '').trim();
}

async function findEstimateByNumber(estNumber: string): Promise<any | null> {
  const num = normalizeEstNumber(estNumber);
  if (!num) return null;
  try {
    // Exact first (works on Postgres + D1 shim).
    const exact = await (prisma as any).estimate.findFirst({ where: { estimateNumber: num } });
    if (exact) return exact;
  } catch { /* fall through to scan */ }
  try {
    // Case/whitespace-tolerant fallback scan (small table, rare path).
    const all = await (prisma as any).estimate.findMany({ select: { estimateId: true, estimateNumber: true } });
    const want = num.toLowerCase();
    const hit = (all as any[]).find((e) => String(e?.estimateNumber ?? '').trim().toLowerCase() === want);
    if (!hit) return null;
    return (prisma as any).estimate.findUnique({ where: { estimateId: String(hit.estimateId) } });
  } catch {
    return null;
  }
}

async function telecallerName(id: string | null | undefined): Promise<string | null> {
  if (!id) return null;
  try {
    const t = await (prisma as any).telecaller.findUnique({ where: { id: String(id) }, select: { name: true } });
    return (t as any)?.name ? String((t as any).name) : null;
  } catch {
    return null;
  }
}

/** Overwrite Estimate.createdBy from the enquiry's agent — always wins. */
export async function syncEstimateCreatorFromEnquiry(
  estNumber: unknown,
  agentId: unknown,
): Promise<{ updated: boolean; estimateId?: string }> {
  const num = normalizeEstNumber(estNumber);
  const agent = String(agentId ?? '').trim();
  if (!num || !agent) return { updated: false };
  try {
    const est = await findEstimateByNumber(num);
    if (!est) return { updated: false };
    if (String((est as any).createdBy ?? '') === agent) return { updated: false, estimateId: String(est.estimateId) };
    await (prisma as any).estimate.update({
      where: { estimateId: String(est.estimateId) },
      data: { createdBy: agent },
    });
    return { updated: true, estimateId: String(est.estimateId) };
  } catch {
    return { updated: false };
  }
}

/**
 * Reconcile one estimate number after an unlink (EST No. edited away or
 * enquiry deleted): another mapping enquiry wins (first agent found), else
 * createdBy is cleared — By shows ONLY while a B2B enquiry maps the row.
 * Fail-open, never throws.
 */
export async function reconcileEstimateCreator(estNumber: unknown): Promise<{ updated: boolean }> {
  const num = normalizeEstNumber(estNumber);
  if (!num) return { updated: false };
  try {
    const est = await findEstimateByNumber(num);
    if (!est) return { updated: false };
    let owner: string | null = null;
    try {
      const rows = await (prisma as any).enquiry.findMany({});
      for (const r of rows as any[]) {
        if (normalizeEstNumber((r as any)?.estNumber) !== num) continue;
        const agent = String((r as any)?.assignedAgentId ?? '').trim();
        if (agent) { owner = agent; break; }
      }
    } catch { /* treat as unmapped below */ }
    const current = String((est as any).createdBy ?? '');
    if ((owner ?? '') === current) return { updated: false };
    await (prisma as any).estimate.update({
      where: { estimateId: String(est.estimateId) },
      data: { createdBy: owner },
    });
    return { updated: true };
  } catch {
    return { updated: false };
  }
}

/** Batch Zoho status lookup for the enquiry list (single query, fail-open).
 *  Attached pre-redaction in `enquiryList` so the procurement payload keeps
 *  `zohoStatus` even though `estNumber` itself is blanked below. */
export async function estimateStatusByNumbers(nums: unknown[]): Promise<Map<string, { status: string; customerName: string }>> {
  const out = new Map<string, { status: string; customerName: string }>();
  const uniq = [...new Set((nums as any[]).map(normalizeEstNumber).filter(Boolean))];
  if (!uniq.length) return out;
  try {
    const rows = await (prisma as any).estimate.findMany({
      where: { estimateNumber: { in: uniq } },
      select: { estimateNumber: true, status: true, customerName: true },
    });
    for (const r of (rows as any[]) ?? []) {
      out.set(String((r as any)?.estimateNumber ?? ''), {
        status: String((r as any)?.status ?? ''),
        customerName: String((r as any)?.customerName ?? ''),
      });
    }
  } catch { /* fail-open: rows simply carry no zohoStatus */ }
  return out;
}

/** Lookup for the B2B EST-No. check button. */
export async function lookupEstimateStatus(estNumber: unknown): Promise<{
  found: boolean;
  estimateId?: string;
  estimateNumber?: string;
  customerName?: string;
  status?: string;
  total?: number;
  assignedTelecallerId?: string | null;
  holderName?: string | null;
  createdBy?: string | null;
  creatorName?: string | null;
}> {
  const num = normalizeEstNumber(estNumber);
  if (!num) return { found: false };
  const est = await findEstimateByNumber(num);
  if (!est) return { found: false };
  const [holderName, creatorName] = await Promise.all([
    telecallerName((est as any).assignedTelecallerId ?? null),
    telecallerName((est as any).createdBy ?? null),
  ]);
  return {
    found: true,
    estimateId: String(est.estimateId),
    estimateNumber: String(est.estimateNumber),
    customerName: String(est.customerName ?? ''),
    status: String(est.status ?? ''),
    total: Number(est.total ?? 0),
    assignedTelecallerId: (est as any).assignedTelecallerId ?? null,
    holderName,
    createdBy: (est as any).createdBy ?? null,
    creatorName,
  };
}

/**
 * Claim flow for the B2B button: check exists → if held by someone else,
 * report holder only (no steal); if free, assign to the enquiry's agent
 * AND overwrite createdBy (enquiry always wins). Fail-open, never throws.
 */
export async function claimEstimateForAgent(
  estNumber: unknown,
  agentId: unknown,
  reason = 'B2B enquiry claim',
): Promise<{
  ok: boolean;
  error?: string;
  alreadyAssigned?: boolean;
  alreadyMine?: boolean;
  estimateId?: string;
  holderName?: string | null;
  holderId?: string | null;
}> {
  const num = normalizeEstNumber(estNumber);
  const agent = String(agentId ?? '').trim();
  if (!num) return { ok: false, error: 'Enter EST No. first' };
  if (!agent) return { ok: false, error: 'Enquiry has no Lead By agent' };
  const est = await findEstimateByNumber(num);
  if (!est) return { ok: false, error: 'Estimate not found in Zoho sync yet' };
  const estimateId = String(est.estimateId);
  const holder = (est as any).assignedTelecallerId ? String((est as any).assignedTelecallerId) : null;
  if (holder && holder !== agent) {
    return { ok: false, alreadyAssigned: true, estimateId, holderId: holder, holderName: await telecallerName(holder) };
  }
  if (holder === agent) {
    // Already mine — still ensure creator reflects the enquiry.
    await syncEstimateCreatorFromEnquiry(num, agent);
    return { ok: true, alreadyMine: true, estimateId, holderId: holder, holderName: await telecallerName(holder) };
  }
  // Free → assign + stamp creator (enquiry always wins).
  try {
    await (prisma as any).estimate.update({
      where: { estimateId },
      data: { assignedTelecallerId: agent, createdBy: agent },
    });
    try {
      const { recordAssignment } = await import('../../automations/telecalling/service');
      await recordAssignment(estimateId, agent, reason);
    } catch { /* ledger best-effort */ }
    try {
      const { invalidateRiskCache } = await import('../../automations/telecalling/service');
      await invalidateRiskCache();
    } catch { /* non-fatal */ }
    try {
      const { invalidateDerivedEstimateCaches } = await import('../../shared/estimates-cache');
      await invalidateDerivedEstimateCaches();
    } catch { /* non-fatal */ }
    return { ok: true, estimateId, holderId: agent, holderName: await telecallerName(agent) };
  } catch (e: any) {
    return { ok: false, error: e?.message || 'assign failed' };
  }
}

/** Map of estimateNumber → enquiry agent for a batch (engine creator-first). */
export async function enquiryAgentByEstNumber(estimateNumbers: string[]): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const nums = [...new Set(estimateNumbers.map(normalizeEstNumber).filter(Boolean))];
  if (nums.length === 0) return out;
  try {
    const rows = await (prisma as any).enquiry.findMany({});
    for (const r of rows as any[]) {
      const key = normalizeEstNumber((r as any)?.estNumber);
      const agent = String((r as any)?.assignedAgentId ?? '').trim();
      if (key && agent && nums.includes(key) && !out.has(key)) out.set(key, agent);
    }
  } catch { /* fail-open: engine falls back to createdBy/comment inference */ }
  return out;
}
