import { cached, cacheGet, cacheDel, cacheDelPrefix } from './cache';
import { prisma } from './prisma';
import { logger } from './logger';
import { isSystemGeneratedComment } from './systemComment';

// ── /api/estimates payload cache (KV-backed) ─────────────────────────────────
// The Zoho Estimates dashboard payload includes every open estimate with its
// FULL comment timeline. Dashboards refetch on every runner WebSocket
// broadcast (every 5–15 min), so serving it from a short-TTL KV snapshot cuts
// D1 row reads by ~100×. Same pattern as the telecalling risk cache.
const KEY = 'sales_copilot:estimates_cache';
// Long TTL: the cache is invalidated on real data changes (comments, status,
// classification) by the runner endpoints, so a long TTL only guards against
// expiry-forced recomputes. A short TTL (e.g. 5 min) forced a ~3s cold recompute
// on the next dashboard load every cycle — that was the "backend is slow" bug.
const TTL_MS = 30 * 60 * 1000;

interface EstimatesPayload {
  estimates: any[];
  lastCompleteSyncAt: string | null;
  computedAt: string;
  /** Active Zoho sales orders created today (IST) — fetched by the GH runner,
   *  persisted in KV by /api/runner/zoho/salesorders-today, merged here so the
   *  dashboard gets the "Sales Orders Today" KPI + feed from the SAME endpoint
   *  it already loads (/api/estimates). The automation data() route is
   *  worker-unregistered ("no data provider"), so it must NOT be relied on. */
  salesOrdersToday: { count: number; totalValue: number; statuses: Record<string, number>; orders: any[] };
}

/** Calendar date (YYYY-MM-DD) in IST (+05:30). */
function istDateString(d: Date): string {
  return new Date(d.getTime() + 5.5 * 60 * 60 * 1000).toISOString().slice(0, 10);
}

const EMPTY_SO = { count: 0, totalValue: 0, statuses: {}, orders: [] as any[] };

async function getSalesOrdersToday(): Promise<typeof EMPTY_SO> {
  try {
    const so = await cacheGet<{ date: string; count: number; totalValue: number; statuses: Record<string, number>; orders: any[] }>(
      'zoho:salesorders_today',
      45 * 60 * 1000,
    );
    if (so && so.date === istDateString(new Date()) && typeof so.count === 'number') {
      return { count: so.count, totalValue: so.totalValue || 0, statuses: so.statuses || {}, orders: Array.isArray(so.orders) ? so.orders : [] };
    }
  } catch { /* KV miss → zeros */ }
  return EMPTY_SO;
}

async function computeEstimatesPayload(): Promise<EstimatesPayload> {
  const [estimates, lastCompleteSync, telecallers] = await Promise.all([
    prisma.estimate.findMany({
      where: { OR: [{ status: 'sent' }, { status: 'accepted' }, { status: 'declined' }, { status: 'confirmed' }] },
      include: { classification: true, comments: { orderBy: { commentId: 'desc' } } },
    }),
    prisma.setting.findUnique({ where: { key: 'sales_copilot:last_complete_sync_at' } }),
    prisma.telecaller.findMany({}),
  ]);
  const nameById = new Map(telecallers.map((t: any) => [t.id, t.name]));
  const salesOrdersToday = await getSalesOrdersToday();
  return {
    estimates: estimates.map((e: any) => ({
      ...e,
      // "Lead generated by" = the originating agent (creator) only, not the
      // current holder — hidden until the creator is recorded.
      leadOf: e.createdBy ? nameById.get(String(e.createdBy)) ?? null : null,
      comments: (e.comments || []).filter(
        (c: any) => !isSystemGeneratedComment(c.description, c.commentedBy),
      ),
    })),
    lastCompleteSyncAt: lastCompleteSync?.value ?? null,
    computedAt: new Date().toISOString(),
    salesOrdersToday,
  };
}

/**
 * Invalidate the estimates cache when the underlying Zoho data changes (a
 * runner sync, comment sync, status/classification transition, or bulk upsert).
 * Call sites: the runner endpoints that mutate Estimate/Comment/Classification.
 */
export async function invalidateEstimatesCache(): Promise<void> {
  await cacheDel(KEY);
}

/**
 * Invalidate every derived cache that depends on the estimates payload (e.g.
 * the telecalling KRA attribution reads the same estimates). Called alongside
 * invalidateEstimatesCache() on any mutation.
 */
export async function invalidateDerivedEstimateCaches(): Promise<void> {
  await Promise.all([
    cacheDelPrefix('neodove:kra'),
    cacheDelPrefix('telecalling:risk'),
    cacheDelPrefix('telecalling:dashboard'),
    cacheDel(KEY),
  ]);
}

export async function getEstimatesPayload(): Promise<EstimatesPayload> {
  return cached<EstimatesPayload>(KEY, TTL_MS, async () => {
    const computed = await computeEstimatesPayload();
    logger.debug({ estimates: computed.estimates.length }, 'estimates payload computed');
    return computed;
  });
}