// compile-kyp.mjs — validates data/know_your_product_v2.json, reports prompt
// sizes, and emits the slim edge-safe lookup artifact src/modules/enquiries/kyp-lookup.ts:
// [{ category, item, aliases, required_attributes }] — per-item checklist without notes.
// vision-intake.ts (Worker, edge bundle) imports it for Call-2 lookup + spec completeness
// without paying the full ~98KB catalogue cost.
// Usage: node scripts/compile-kyp.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'data', 'know_your_product_v2.json');

const raw = JSON.parse(readFileSync(src, 'utf8'));
const cats = raw.categories ?? [];
let total = 0;
for (const c of cats) {
  total += (c.items ?? []).length;
  const full = JSON.stringify(c).length;
  console.log(`${c.category}: ${(c.items ?? []).length} items (~${Math.round(full / 4)} stage-B tokens)`);
}
const slim = cats.map((c) => `${c.category}: ${(c.items ?? []).map((i) => i.item_name).join(', ')}`).join('\n');
console.log(`categories: ${cats.length}, items: ${total}`);
console.log(`stage-A router list: ${slim.length} chars (~${Math.round(slim.length / 4)} tokens)`);

// Slim edge artifact: category + item_name + aliases + required_attributes.
// The Worker (vision-intake.ts Call-2 lookup + completeness) imports this — never the full v2 file.
// Lives under src/ so tsc rootDir is satisfied; still GENERATED, do not edit.
const lookup = [];
for (const c of cats) {
  for (const i of (c.items ?? [])) {
    lookup.push({
      category: c.category,
      item: i.item_name,
      aliases: (i.aliases ?? []).filter(Boolean),
      required_attributes: (i.required_attributes ?? []).filter(Boolean),
    });
  }
}
const ts = `// GENERATED by scripts/compile-kyp.mjs from data/know_your_product_v2.json — DO NOT EDIT.\n// Slim artifact: category + item + aliases + required_attributes (no notes).\n// Re-run compile-kyp.mjs after editing v2.\nexport interface KypLookupEntry { category: string; item: string; aliases: string[]; required_attributes: string[]; }\nexport const KYP_LOOKUP: KypLookupEntry[] = ${JSON.stringify(lookup)};\n`;
writeFileSync(join(root, 'src', 'modules', 'enquiries', 'kyp-lookup.ts'), ts);
console.log(`kyp-lookup.ts: ${lookup.length} entries`);
console.log('v2 OK — no derived files needed.');
